/*
 * config.h - ESP32S3 CAN to Modbus TCP Bridge Configuration
 * 
 * VERSION: v4.0.0 - MODULAR ARCHITECTURE
 * DATE: 2025-08-12
 * DESCRIPTION: Centralna konfiguracja systemu ESP32S3 CAN to Modbus TCP Bridge
 */

#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>
#include <mcp_can.h>

// === FIRMWARE INFORMATION ===
#define FIRMWARE_VERSION "v4.0.0"
#define BUILD_DATE __DATE__ " " __TIME__
#define DEVICE_NAME "ESP32S3-CAN-Modbus-Bridge"

// === DEBUG CONFIGURATION ===
#define ENABLE_DEBUG_SERIAL 1
#define ENABLE_CAN_FRAME_LOGGING 1
#define ENABLE_MODBUS_FRAME_LOGGING 1
#define ENABLE_WIFI_LOGGING 1

#if ENABLE_DEBUG_SERIAL
  #define DEBUG_PRINT(x) Serial.print(x)
  #define DEBUG_PRINTLN(x) Serial.println(x)
  #define DEBUG_PRINTF(fmt, ...) Serial.printf(fmt, ##__VA_ARGS__)
#else
  #define DEBUG_PRINT(x)
  #define DEBUG_PRINTLN(x)
  #define DEBUG_PRINTF(fmt, ...)
#endif

// === HARDWARE CONFIGURATION ===

// SPI Pins for MCP2515 CAN Controller
#define SPI_CS_PIN    44
#define SPI_MOSI_PIN  9
#define SPI_MISO_PIN  8
#define SPI_SCK_PIN   7
#define CAN_INT_PIN   2

// Other Hardware Pins
#define LED_PIN       21

// === SYSTEM LIMITS ===
#define MAX_BMS_NODES 16
#define MAX_WIFI_SSID_LENGTH 32
#define MAX_WIFI_PASSWORD_LENGTH 64
#define MAX_IP_ADDRESS_LENGTH 16
#define MAX_DEVICE_NAME_LENGTH 32

// === CAN CONFIGURATION ===
#define CAN_SPEED_125K CAN_125KBPS
#define CAN_SPEED_250K CAN_250KBPS
#define CAN_SPEED_500K CAN_500KBPS

// CAN Frame Types and Base IDs
#define BMS_FRAME_190_BASE 0x180  // Basic data (voltage, current, SOC)
#define BMS_FRAME_290_BASE 0x280  // Cell voltages (min, mean)
#define BMS_FRAME_310_BASE 0x300  // SOH, temperature, impedance
#define BMS_FRAME_390_BASE 0x380  // Max voltages
#define BMS_FRAME_410_BASE 0x400  // Temperatures, ready states
#define BMS_FRAME_510_BASE 0x500  // Power limits, I/O states
#define BMS_FRAME_490_BASE 0x480  // Multiplexed data
#define BMS_FRAME_1B0_BASE 0x1A0  // Additional data
#define BMS_FRAME_710_BASE 0x700  // CANopen status

// CAN Timing
#define CAN_RESET_DELAY_MS 100
#define CAN_INIT_TIMEOUT_MS 5000
#define CAN_FRAME_TIMEOUT_MS 1000

// === MODBUS TCP CONFIGURATION ===
#define MODBUS_TCP_PORT 502
#define MODBUS_SLAVE_ID 1
#define MODBUS_MAX_HOLDING_REGISTERS 2000
#define MODBUS_REGISTERS_PER_BMS 125
#define MODBUS_CLIENT_TIMEOUT_MS 30000

// === WIFI CONFIGURATION ===
#define DEFAULT_WIFI_SSID "WNK3"
#define DEFAULT_WIFI_PASSWORD "PiotrStrzyklaskiNieIstnieje"
#define DEFAULT_DEVICE_IP "DHCP"

// WiFi Timeouts
#define WIFI_CONNECTION_TIMEOUT_MS 30000
#define WIFI_RECONNECT_DELAY_MS 5000
#define WIFI_MAX_RECONNECT_ATTEMPTS 5

// === BMS DATA CONFIGURATION ===
#define BMS_DATA_TIMEOUT_MS 30000
#define BMS_CRITICAL_TIMEOUT_MS 10000
#define BMS_HEARTBEAT_INTERVAL_MS 5000

// BMS Value Limits
#define BMS_MIN_VOLTAGE 30.0
#define BMS_MAX_VOLTAGE 60.0
#define BMS_MIN_TEMPERATURE -40
#define BMS_MAX_TEMPERATURE 85
#define BMS_MIN_SOC 0.0
#define BMS_MAX_SOC 100.0

// === EEPROM CONFIGURATION ===
#define EEPROM_SIZE 512
#define EEPROM_MAGIC 0xA5
#define EEPROM_MAGIC_VALUE 0xA5

// EEPROM Memory Map
#define EEPROM_MAGIC_ADDR 0
#define EEPROM_WIFI_SSID 1
#define EEPROM_WIFI_PASS (EEPROM_WIFI_SSID + MAX_WIFI_SSID_LENGTH)
#define EEPROM_DEVICE_IP (EEPROM_WIFI_PASS + MAX_WIFI_PASSWORD_LENGTH)
#define EEPROM_ACTIVE_BMS (EEPROM_DEVICE_IP + MAX_IP_ADDRESS_LENGTH)
#define EEPROM_BMS_IDS (EEPROM_ACTIVE_BMS + 1)
#define EEPROM_CAN_SPEED (EEPROM_BMS_IDS + MAX_BMS_NODES)

// === SYSTEM STATES ===
typedef enum {
  SYSTEM_STATE_INIT = 0,
  SYSTEM_STATE_INITIALIZING,
  SYSTEM_STATE_RUNNING,
  SYSTEM_STATE_ERROR,
  SYSTEM_STATE_RECOVERY,
  SYSTEM_STATE_SHUTDOWN
} SystemState_t;

// === CAN STATES ===
typedef enum {
  CAN_STATE_UNINITIALIZED = 0,
  CAN_STATE_INITIALIZING,
  CAN_STATE_RUNNING,
  CAN_STATE_ERROR,
  CAN_STATE_RECOVERY
} CanState_t;

// === CAN ERRORS ===
typedef enum {
  CAN_ERROR_NONE = 0,
  CAN_ERROR_INIT_FAILED,
  CAN_ERROR_MODE_FAILED,
  CAN_ERROR_FILTER_FAILED,
  CAN_ERROR_COMMUNICATION_FAILED,
  CAN_ERROR_TIMEOUT,
  CAN_ERROR_HARDWARE_FAULT
} CanError_t;

// === MODBUS STATES ===
typedef enum {
  MODBUS_STATE_UNINITIALIZED = 0,
  MODBUS_STATE_INITIALIZING,
  MODBUS_STATE_RUNNING,
  MODBUS_STATE_ERROR,
  MODBUS_STATE_CLIENT_CONNECTED
} ModbusState_t;

// === BMS FRAME TYPES ===
typedef enum {
  BMS_FRAME_TYPE_190 = 0,  // Basic data
  BMS_FRAME_TYPE_290,      // Cell voltages
  BMS_FRAME_TYPE_310,      // SOH/Temperature
  BMS_FRAME_TYPE_390,      // Max limits
  BMS_FRAME_TYPE_410,      // Temperatures
  BMS_FRAME_TYPE_510,      // Power limits
  BMS_FRAME_TYPE_490,      // Multiplexed
  BMS_FRAME_TYPE_1B0,      // Additional
  BMS_FRAME_TYPE_710,      // CANopen
  BMS_FRAME_TYPE_COUNT
} BMSFrameType_t;

// === CONFIGURATION